# Generated by Django 5.1.2 on 2024-10-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestInfoDashboard',
        ),
    ]
