# Generated by Django 5.1.2 on 2024-10-27 16:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_test_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='additional_phone_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='additional_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
