# Generated by Django 5.1.2 on 2024-12-21 03:39

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('IR', 'In a Relationship'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widow')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to=apps.accounts.models.profile_photo_directory_path),
        ),
    ]
