# Generated by Django 5.1.2 on 2024-12-26 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email_alter_user_marital_status_and_more'),
        ('doctor_dashboard', '0002_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_dashboard.specialization'),
        ),
    ]
