# Generated by Django 5.1.2 on 2024-12-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_education_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='specialization',
        ),
    ]
