# Generated by Django 5.1.2 on 2024-12-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_education_specialization'),
        ('doctor_dashboard', '0002_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='specialization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doctor_dashboard.specialization'),
        ),
    ]
