# Generated by Django 5.1.2 on 2024-12-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_training_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
