# Generated by Django 5.1.2 on 2025-01-10 10:12

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_experience_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profile/avatar/blank-profile-picturepng.png', upload_to=apps.accounts.models.profile_photo_directory_path),
        ),
    ]
