# Generated by Django 5.1.2 on 2024-10-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_of_birth_alter_user_identity_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_proof',
            field=models.FileField(upload_to='media/identity_proof/<function user_directory_path at 0x000001EDBF3D5A80>'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='media/profile_photo/<function user_directory_path at 0x000001EDBF3D5A80>'),
        ),
    ]
