# Generated by Django 5.1.2 on 2024-10-16 02:31

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_date_of_birth_alter_user_identity_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_proof',
            field=models.FileField(upload_to=accounts.models.identity_type_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity_type',
            field=models.IntegerField(choices=[(1, 'Passport'), (2, 'Nid')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to=accounts.models.profile_photo_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.bloodgroup'),
        ),
    ]
