# Generated by Django 5.1.2 on 2024-10-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bloodgroup_alter_user_identity_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.IntegerField(choices=[(1, 'Verified'), (2, 'Not Verified'), (3, 'Pending'), (4, 'Rejected')], null=True),
        ),
    ]
