# Generated by Django 5.1.2 on 2025-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_dashboard', '0002_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='expert',
            name='doc_title',
            field=models.IntegerField(blank=True, choices=[(1, 'Professor Dr.'), (2, 'Assistant Professor Dr.'), (3, 'Associate Professor Dr.'), (4, 'Distinguished Professor Dr.'), (5, 'Dr.')], default=None, null=True),
        ),
    ]
