# Generated by Django 5.1.2 on 2024-11-02 15:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_delete_testinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsignsreport',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='vitalsignsreport',
            name='sugar_level',
        ),
        migrations.AddField(
            model_name='vitalsignsreport',
            name='diastolic',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='vitalsignsreport',
            name='systolic',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='vitalsignsreport',
            name='checkup_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='BloodSugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_level', models.FloatField(blank=True)),
                ('checkup_date', models.DateTimeField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
