# Generated by Django 5.1.2 on 2024-12-21 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_vitalsignsreport_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalinfo',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=8),
        ),
        migrations.AlterField(
            model_name='biologicalinfo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8),
        ),
        migrations.AlterField(
            model_name='bloodsugar',
            name='checkup_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bloodsugar',
            name='sugar_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vitalsignsreport',
            name='diastolic',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vitalsignsreport',
            name='systolic',
            field=models.PositiveIntegerField(),
        ),
    ]
